Vitaly
GrozaMorei/InvestGROUP pull request #8
Opened 2024-11-29 22:20 UTC by GrozaMorei

### Результаты на _29.11_
1. Настроили порядок импортов
2. Привели цвета к одному формату
3. Доработали структуру категорий и товаров 
4. Сделали проверки на ошибки отсутствия категории или товара
5. Обновили json продуктов и категорий 
6. Переработали принцип работы хлебных крошек
7. Переписали их стили 
8. Разработали и вынесли в отдельный компонент аккордеон (на чистом html и css)
9. Обновили некоторые ссылки на страницах 
10. Почистили проект от лишних зависимостей
11. Залили на "хостинг" (теперь нас можно потыкать)
12. Чуть не удалили весь проект (бонус)
13. Другие исправления по мелочи

_Чем ближе к декабрю, тем выше нагрузка по учебе, времени совсем нет...
К 5 декабрю страницу категорий закончить точно не получится_

**ТЫКАТЬ здесь:** https://invest-group.vercel.app/

> В команде работают два человека👉👈

2024-12-04 06:38 UTC, olya-yevsieienko requested changes
Молодцы, хорошо поработали!
Если есть проблема с локализацей, предлагаю вам отложить пока что на будущее её подключение. Раз уж вас два человека, лучше сконцентрируйтесь на вертске и построении логики.

Молодцы, что настроили стенд!
1. Секциям лучше задавать паддинги. Если мы кликаем на каталог, то скроллит к категориям и блок приклеен к верху страницы. 
![image](https://github.com/user-attachments/assets/6ea9d6e2-127e-4aa1-a26d-986f2c0643cb).
![image](https://github.com/user-attachments/assets/bf2f1073-4e37-4b51-9792-f27ad8655688)
2. При открытии меню должно быть overflow: hidden у body, чтобы нельзя было скроллить контент страницы.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/[category]/[product]/page.jsx
> +  const article = product;
А для чего создавать отдельную константу? Можно просто использовать product сразу)

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/[category]/page.jsx
> +  const categories = ["household-chemicals", "cosmetics-and-hygiene", "household-goods", "products-for-children-and-mothers", "tableware"]
```suggestion
  const categories = ["household-chemicals", "cosmetics-and-hygiene", "household-goods", "products-for-children-and-mothers", "tableware"];
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/[category]/page.jsx
> +  )
```suggestion
  return (
    <>
      <Undefine message={ "страница еще не готова" } />
    </>
  );
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/[category]/page.jsx
> +  }
```suggestion
  if (!isCategoryValid) {
    return (
      <Undefine message={ "категория не найдена" } />
    );
  }
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/about/page.jsx
> +}
В конце каждого файла должна быть одна пустая строка в конце файла

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/about/page.jsx
> +      <h1 className="test-title">Страница: О нас</h1>
Перевод.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Baner/Baner.jsx
> +}
Проверить форматирование, тут явно больше отступов, чем в других файлах.
И пустая строка в конце)

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Baner/Baner.scss
> +			position: absolute;
И в этом файле бюольшие оступы.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Baner/Baner.scss
> +			@media(max-width: $desktop) {
```suggestion
			@media (max-width: $desktop) {
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Baner/Baner.scss
> +			@media(max-width: $tablet) {
```suggestion
			@media (max-width: $tablet) {
```
Проверить везде)

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +'use client'
```suggestion
'use client';
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +  return (
```suggestion
  }

  return (
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +  }
Эту кнопку лучше сделать отдельным компонентом и туда вынести эту логику. Она ведь будет использоваться и на других страницах)

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +
```suggestion
}

```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +  }
Это лучше вынести в файл с константами.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +            return (
В return должна быть только верстка и условная отрисовка, никакого создания констант и логики, иначе будут какие-то сайд-эффекты и сложно будет читать код.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +          <span>Назад</span>
Вот эту кнопку нужно делать отдельным компонентом)

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Crumbs/Crumbs.jsx
> +      </div>
```suggestion
        </button>
      </div>
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Header/Header.jsx
> +
```suggestion
export default function Header() {
     const [isOpen, setIsOpen] = useState(false);

```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Header/Header.jsx
> +									<span className='header-top__subtitle'>На связи в любое время</span>
Проверить форматирование.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/Header/Header.jsx
> +						</nav>
Навигацию нужно сделать ещё и списком.

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/ProductInfo/ProductInfo.jsx
> +						</Accordion>
🔥

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/PromotionalProducts/PromotionalProducts.jsx
> +import products from '@/data/products.json';
Порядок подключения импортов (отправляла в общий чат).

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/UI/Accordion/Accordion.jsx
> +              alt='Иконка стерлочки'
```suggestion
          <span className={`accordion__title ${ className }`} role='term'>
            { title }
            <img 
              src='/icons/arrow-gray.svg'
              alt='Иконка стерлочки'
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/UI/Accordion/Accordion.jsx
> +        </div>
```suggestion
        <div className='accordion__content-body'>
          { children }
        </div>
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/components/UI/Accordion/Accordion.scss
> +    display: grid;
```suggestion
.accordion {
  &__content {
    display: grid;
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/layout.jsx
>          <main className="main"> {children} </main>
```suggestion
        <main className="main">
            {children}
        </main>
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/app/page.jsx
> +import Baner from './components/Baner/Baner.jsx'
```suggestion
import Banner from './components/Banner/Banner.jsx'
```

2024-12-04 06:38 UTC, olya-yevsieienko commented on src/styles/variables.scss
>  $color-category-active: #f5cd7f65;
```suggestion
$color-gray: #ededed;

$color-category: #c0a67123;
$color-category-active: #f5cd7f65;
```

2024-12-06 11:25 UTC, GrozaMorei commented on src/app/components/Baner/Baner.jsx
> +}
Проверил все файлы, везде отступ 2 пробела, не знаю, в чем причина такого отображения в гит

2024-12-06 14:14 UTC, closed without merging